### ISSUE TITLE
I found YET ANOTHER GOOGLE DRIVE LINK.

### ISSUE THREAD

**Issue by upintheairsheep** [OrIdow6/google-drive-items#11]
https://drive.google.com/drive/u/0/mobile/folders/1py6nxyk-GJUfp0giRLWsGWNtyG0kbjNA

**Comment by upintheairsheep** [comment]
https://drive.google.com/drive/u/0/mobile/folders/1V9T_uGR6uKGm_gcVkhdpDnlNAAgMMIdx?usp=sharing

**Comment by OrIdow6** [comment]
This project is inactive.
