### ISSUE TITLE
More requests

### ISSUE THREAD

**Issue by upintheairsheep** [OrIdow6/google-drive-items#5]
I have many google drive links you need to archive. Sadly, it’s all links: google drive, google docs, google sheets, google slides, and a google app scripts link.

Here is a list: https://www.mediafire.com/file/pvv425owrkwt6ds/Blank+8.rtf/file
(Don’t worry I already submitted the mediafire link to the url list)

**Comment by OrIdow6** [comment]
As the pad says, please submit this to the issues of ArchiveTeam/google-drive-items, not my repo.

**Comment by OrIdow6** [comment]
Oh, sorry, didn't realize the issues were closed there.

**Comment by upintheairsheep** [comment]
Can you add them to the list my PC is crap

**Comment by upintheairsheep** [comment]
Is it archived?

**Comment by upintheairsheep** [comment]
Submitted into quene
